spring.application.name=ahorcado-api
# Configuración de la base de datos H2 en memoria
spring.datasource.url=jdbc:h2:mem:ahorcado_db
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Configuración de JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
# update: crea o actualiza las tablas basándose en tus clases Java
spring.jpa.hibernate.ddl-auto=create 
spring.jpa.show-sql=true

# Habilitar la consola web de H2 para ver los datos desde el navegador
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console